### ISSUE TITLE
Run in production

### ISSUE THREAD

**Issue by jonnysmillie** [arwes/arwes#1]
I would find it really useful if you included some instructions for deploying to and running on a server.

**Comment by romelperez** [comment]
Hi @jonnysmillie! Yes, that's in the planning. Arwes supports server-side rendering, currently I am using [next.js](https://github.com/zeit/next.js/) with Arwes and it works, for the [arwes website](https://arwes.romelperez.com) and [my website](https://romelperez.com).

You can review the [source code of the website](https://github.com/romelperez/romelperez.com) meanwhile.

**Comment by jonnysmillie** [comment]
oh wow that's very cool. I will take a look. thanks a lot 👍

**Comment by DaveGeneral** [comment]
very cool work, buddy!

**Comment by romelperez** [comment]
Hello! The latest release includes information about running the project regardless of the environment 😄 You can check it out at https://arwes.dev.

**Comment by DaveGeneral** [comment]
这是来自QQ邮箱的假期自动回复邮件。已收到，-_-
