### ISSUE TITLE
Add TextField component

### ISSUE THREAD

**Issue by romelperez** [arwes/arwes#112]
Create an input component to handle input text and textarea elements.

- [x] Create `TextField` component.
- [x] Add `multiline: boolean = false` prop to enable textarea. Otherwise it creates an input element.
- [x] When `multiline = false`, create input element with possible types: `['text', 'email', 'search', 'password', 'tel', 'url', 'number']`.
- [x] Allow basic props and events passed down to the real input/textarea element.
- [x] Add `palette: string` prop.
- [x] If animated and autoFocus enabled, focus element on animator entering.
- [x] If animated, remove input focus on animator exiting.
- [x] Animate text placeholder if provided on transitions.
- [x] Animate text value/defaultValue if provided on transitions.

**Comment by Nexuist** [comment]
Would this support input types like 'datetime', 'email', 'number', 'checkbox' etc?

Thank you a lot for your work!

**Comment by romelperez** [comment]
Hey @Nexuist, by default the component creates an `Input` with possible types: `['text', 'email', 'search', 'password', 'tel', 'url', 'number']`, unless the component is `multiline` which will turn it into a `Textarea`. :smiley:

**Comment by Nexuist** [comment]
This is awesome. Looking forward to it!
