### ISSUE TITLE
Access legacy buttons

### ISSUE THREAD

**Issue by InsOpDe** [arwes/arwes#114]
## Is your feature request related to a problem? Please describe

Im currently working with an older version of arwes with the old buttons. I do want to update the arwes version, which would also mean that the old buttons will be exchagned for the new ones.

I like the new ones but I'd like to keep the old ones, as well.

## Describe the solution you'd like

I'd like to have a possibility to import the legacy buttons

## Describe alternatives you've considered

I could have two versions of arwes installed, but that would bloat my codebase. I also looked into the deprecated folder of this repo but couldnt find them.

## Additional context

Im talking about these:
![image](https://user-images.githubusercontent.com/10099328/114274840-925afe80-9a20-11eb-9d5b-282166031e2f.png)

they still fit very well into arwes imho

**Comment by romelperez** [comment]
Hello @InsOpDe !

In the last weeks I've been working precisely on the new frames for the latest project version. It will include the same frame which was in the previous project version and many more. So there is no need to mix the two.

The idea is to release a batch of them in the next alpha release. Though they will still not be ready for production yet.

Stay tuned for updates!

**Comment by romelperez** [comment]
Closed due to https://github.com/arwes/arwes/issues/46#issuecomment-1639308400
