### ISSUE TITLE
Refactor Text transition animation functionality

### ISSUE THREAD

**Issue by romelperez** [arwes/arwes#136]
**RELATES TO #85**

----

The `Text` component uses `useLayoutEffect` hook to check the text data for the transition animations. Though it still works for server-side rendering, React compilation throws an error about it.

- [ ] Refactor to not use `useLayoutEffect` functionalities since this component will be used for server-side rendering.

**Comment by fyroc** [comment]
I just want to note that NextJS won't compile because of those error
