### ISSUE TITLE
How to Pass onError to Image component?

### ISSUE THREAD

**Issue by ReactGirl** [arwes/arwes#17]
I need to handle the source in case the image does not exist.
How can I pass onError event handler to Image as the same way below.

Working code using img html tag.
```
<img
    src={photoUrl}
    onError={e => {
      if (e.target.src !== photoFallBack) {
        e.target.src = photoFallBack
      }
    }}
  />
```
However if I change the img to arwes Image component, updating the 'src' to 'resources' it does not work.

**Comment by romelperez** [comment]
Hi @ReactGirl !

Currently, the component does not provide an API to handle image errors. Though if you update the provided `resources` to the component, it will try to update the image if correct.

My suggestion is that you pre-fetch the images before you pass them to the components and if they load, render the images.

Let me know if I can help you with that. We can chat on Discord. The link in the project README.

Thanks for using Arwes though it is still in alpha :)

**Comment by ReactGirl** [comment]
This is a great project. Do you think this can be a feature request in the feature? Thanks

**Comment by romelperez** [comment]
Ok, perfect.
Yes, definitely!
I am still making progress in the side project [soulextract.com](https://github.com/soulextract/soulextract.com) to research new features for Arwes. But once I reopen development in Arwes, this and many more features can be reviewed and added if considered, so keep sharing your thoughts and problems with the framework, they are really helpful.
Thanks for using Arwes @ReactGirl !
