### ISSUE TITLE
support React 18

### ISSUE THREAD

**Issue by amir-arad** [arwes/arwes#178]
I can't upgrade to React 18 due to typescript errors with Arwes

## Describe the solution you'd like

Support React 18 types

## Describe alternatives you've considered

for now I dont upgrade React. no biggie

## Additional context

some example errors:

```sh
Type '{ children: (string | number | Element)[]; animator: { duration: { enter: number; exit: number; }; activate: boolean; }; }' is not assignable to type 'IntrinsicAttributes & TextProps & WithAnimatorOutputProps'.
  Property 'children' does not exist on type 'IntrinsicAttributes & TextProps & WithAnimatorOutputProps'.

64             <Text animator={{ duration, activate: broken }}>
                ~~~~

Type '{ children: Element[]; }' has no properties in common with type 'IntrinsicAttributes & ArwesThemeProviderProps'.

115                 <ArwesThemeProvider>
                     ~~~~~~~~~~~~~~~~~~
                     
Type '{ children: Element; audioSettings: { common: { volume: number; }; }; playersSettings: { object: { src: string[]; }; type: { src: string[]; loop: boolean; }; }; bleepsSettings: { object: { player: string; }; type: { ...; }; }; }' is not assignable to type 'IntrinsicAttributes & BleepsProviderProps'.
  Property 'children' does not exist on type 'IntrinsicAttributes & BleepsProviderProps'.

117                     <BleepsProvider
                         ~~~~~~~~~~~~~~
```
Et cetera

a full printout can be found [here](https://app.circleci.com/pipelines/github/starwards/starwards/1468/workflows/527eaae6-ab5c-4b21-97df-e46a66e7c350/jobs/2346/parallel-runs/0/steps/0-111). and the source is this [PR](https://github.com/starwards/starwards/pull/844).

**Comment by cryptosunshine** [comment]
Is there any latest progress?

**Comment by romelperez** [comment]
@cryptosunshine , not yet released, still work in progress.

**Comment by amir-arad** [comment]
may be related: also support the new Typescript :(
starwards/starwards#1351

**Comment by romelperez** [comment]
The project was migrated completely to TypeScript and support for only React v18. Though the development is still in progress with the releases made with the `next` tag on NPM. Let me know if you have any questions on Discord 😄
