### ISSUE TITLE
Input  does not work inside a Card component. (IOS)

### ISSUE THREAD

**Issue by inPhoenix** [arwes/arwes#183]
## Describe the bug

There is something wrong with the input component inside the Card component. 
Code: https://github.com/inPhoenix/inCyberText
Link Live: https://inphoenix.github.io/inCyberText/

## To reproduce

Access using IOS: https://inphoenix.github.io/inCyberText/
Try to add something to the input using iPhone IOS Chrome/Safari.

## Expected behaviour
On desktop/computer everything works fine. 
Note: I had to put "relative" CSS on the input class wrapper to have it work on the desktop, but it fails when accessed by Mobile IOses. (not tested with Android)

## Screenshots

<img width="1075" alt="Screenshot 2022-09-07 at 16 32 46" src="https://user-images.githubusercontent.com/17971878/188961874-18d0090d-78e1-473c-902e-74cd912be659.png">

## Development environment

React 18

## Testing environment

- Device: iPhone 13 / IOS 15.6.1
- Browser: Chrome / Safari 
- arwes 1.0.0-alpha.19

**Comment by romelperez** [comment]
Closed due to https://github.com/arwes/arwes/issues/46#issuecomment-1639308400
