### ISSUE TITLE
Add markdown linter

### ISSUE THREAD

**Issue by romelperez** [arwes/arwes#19]
**DEPENDS ON #18**

----

To ensure everyone follows a convention when documenting in markdown, a markdown linter would be useful to be set up in the project workflow.

- [x] Research markdown linter solutions.
- [x] Set it up in the project.

**Comment by giovanisleite** [comment]
Hi!

I would like to contribute to the project. This issue seems an interesting way of starting!
I will work on it =)

**Comment by romelperez** [comment]
Hi @giovanisleite !

I am sorry, I haven't updated the tasks on the boards because of time. But this is kinda completed. I added [markdownlint](https://www.npmjs.com/package/markdownlint) :sweat_smile: 

For now, I have two tasks in the [sounds board](https://github.com/arwes/arwes/projects/4). Let me know if you are interested. :wink: 

Thank you!

**Comment by giovanisleite** [comment]
Sure! It seems challenging. I will try it!

**Comment by romelperez** [comment]
Yes, thank you @giovanisleite !
