### ISSUE TITLE
React-JSS has theming

### ISSUE THREAD

**Issue by kof** [arwes/arwes#2]
Feel free to use React-JSS theming solution directly, just in case you missed when it was added.

**Comment by romelperez** [comment]
Awesome! I am gonna review it @kof, thank you!

**Comment by romelperez** [comment]
Hey @kof! 👋 Arwes is no longer using JSS under the hood, and also the framework has transitioned more to a low-to-medium level toolset for sci-fi effects, rather than an entire UI framework, so no styling solution is coupled now to the project. Thank you anyway for pointing this out at that time! 😄
