### ISSUE TITLE
Console show warning 

### ISSUE THREAD

**Issue by hajirasyafi** [arwes/arwes#201]
console show warning :

**Warning: Dots: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.**

I'm using NextJS 13.4.3 with app directory

- node 16.14.2
- npm 8.5.0
- OS : macOS Ventura 13.3.1

list dep : 
```
"dependencies": {
    "@arwes/react": "^1.0.0-next.7",
    "@arwes/react-animated": "^1.0.0-next.7",
    "@arwes/react-animator": "^1.0.0-next.7",
    "@arwes/react-bgs": "^1.0.0-next.7",
    "@arwes/react-bleeps": "^1.0.0-next.7",
    "@arwes/react-core": "^1.0.0-next.7",
    "@arwes/react-frames": "^1.0.0-next.7",
    "@arwes/react-text": "^1.0.0-next.7",
    "@arwes/react-tools": "^1.0.0-next.7",
    "@types/node": "20.2.1",
    "@types/react": "18.2.6",
    "@types/react-dom": "18.2.4",
    "autoprefixer": "10.4.14",
    "eslint": "8.41.0",
    "eslint-config-next": "13.4.3",
    "next": "13.4.3",
    "postcss": "8.4.23",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "tailwindcss": "3.3.2",
    "typescript": "5.0.4"
  }
```
<img width="858" alt="Jepretan Layar 2023-05-23 pukul 00 54 33" src="https://github.com/arwes/arwes/assets/46818416/e8165ca7-fd85-4837-b467-703c0133cc5b">

**Comment by romelperez** [comment]
Hello @hajirasyafi !

If you want to contribute and remove the default props from all `@arwes/react-bgs` components (not just `Dots`), it would be great. Let me know if you want and have any questions. Otherwise, I'll work on this one for the next release.

Thank you for reporting!

**Comment by hajirasyafi** [comment]
Thanks for reply,
Im sorry, maybe for now i only reporting, because I'm still learning Typescript and react fundamental. I hope in future i can help your project.
