### ISSUE TITLE
Research audio availability management

### ISSUE THREAD

**Issue by romelperez** [arwes/arwes#25]
Currently, [Chrome has some audio policies](https://developers.google.com/web/updates/2018/11/web-audio-autoplay) which prevent sounds being played before a user interacts with a website. Usually, the applications would need to play sounds at start time, we need to identify possible and proper ways to handle this scenario.

1) Should we always show an alert/button/modal component to ask the user to interact with the page to experience it properly?
2) Should we let the user enter the website right away and resume playing sounds once the user interacts with the website?
3) Should we let the user enter the website without checking for interactions?
4) Should there be any functionality by default in the components to handle these scenarios?

**Comment by njwest** [comment]
From a web design perspective, the user should encounter as little friction as possible when experiencing a website, and they should be able to experience the website as fast as possible.

1. Should we always show an alert/button/modal component to ask the user to interact with the page to experience it properly?

No, we should not make this default behavior. 

We should make it clear at the beginning of the Arwes audio docs that on Chrome and some other browsers, audio won't play until a user interacts with the site, and if a dev is developing a site on which sounds absolutely must run upon entry, they should have a splash page with an ENTER or START button or something like that. 

We can provide an example of this, or even a prefab component such as the one outlined in my answer to 4 below.

2. Should we let the user enter the website right away and resume playing sounds once the user interacts with the website?

This should be the default behavior for the smoothest user experience. See answer to #1 for a way to easily accommodate experiences that require sounds out of the box. 

3. Should we let the user enter the website without checking for interactions?

Yes

4. Should there be any functionality by default in the components to handle these scenarios?

Per answer to #1, we could provide an ENTER screen that is turned off by default. 

One potential design: prop on the parent Arwes component that defaults to `false` called `showEnterScreen`, that if true renders an initial entry screen with the ENTER button horizontally and vertically centered.

When the ENTER button is pressed, run, flip the `showEnterScreen` boolean and run the contents of the parent Arwes component.
 
```js
<Arwes showEnterScreen={true} enterButtonText="START">
      ...
</Arwes>
```
 
**Note:** I think a solution like the one outlined in 4 above would be a nice-to-have feature, but not a necessary feature for a 1.0 release.

**Comment by romelperez** [comment]
_I include this chat in the Discord `#sounds` channel related to this issue:_

![Screenshot from 2020-12-07 15-41-46](https://user-images.githubusercontent.com/1393135/101403604-79d8ad00-38a3-11eb-8046-adcb016cc980.png)

**Comment by romelperez** [comment]
Based on the comments, the conclusions are as follows:

1) For better UX, by default Arwes should not ask/recommend for "user interactivity for sound playback" unless the programmer explicitly require it from the user.
2) An optional application component behavior can be added to allow the programmer to set this up out of the box.
3) There should be "categories of sound playback" to allow the programmer and the user to set up in the UX. For example, enable/disable or change volume of certain types of sounds in the application.

The implementation APIs of these features should be handled in another task.

**Comment by romelperez** [comment]
The new sounds tooling API has been defined in https://github.com/arwes/arwes/issues/81. There, the conclusions reached in this task has been attended in different approaches. Documentation will be required to guide the programmer as to how to implement these user experiences.
