### ISSUE TITLE
Is <List/> has animation?

### ISSUE THREAD

**Issue by DongheePaul** [arwes/arwes#27]
### Subject of the issue

Hi. 
I want to know List component has animation or not

In this site(https://arwes.dev/docs), I think List has animation.
So I use List tag in my application made by referring to Arwes website(https://arwes.dev/play#list), but there is no animation.

Would you please answer that is List component has animation or not?

If List component doesn't have animation, what is the component that seems like List in (https://arwes.dev/docs) ?

**Comment by DongheePaul** [comment]
![스크린샷 2019-06-29 오후 8 17 45](https://user-images.githubusercontent.com/50191479/60383434-797f9400-9aab-11e9-8008-d3d82e65f3d1.png)

**Comment by romelperez** [comment]
Hi @DongheePaul! Thanks for using Arwes.

The components under the "STATICS" label in https://arwes.dev/api are not animated. They have to be animated from an upper level in the components tree.

Except for "PROVIDERS" and "STATICS", all other components are animated.

You can use the https://arwes.dev/api/appear component for that.

**Comment by DongheePaul** [comment]
Thank you for your answer.
I hope you get well soon 🙏
