### ISSUE TITLE
Is there a way to integrate Arwes with Next.js?

### ISSUE THREAD

**Issue by DennisSSDev** [arwes/arwes#41]
### Arwes not supported for SSR?

I was trying to get Arwes to work with NextJS, but started to running into rendering exceptions like this
<img width="743" alt="Screen Shot 2019-11-16 at 8 27 50 PM" src="https://user-images.githubusercontent.com/26827854/69001632-4732cf80-08b0-11ea-8bfe-4ffd4168b762.png">

Any idea how to solve this issue? 

Repo: https://github.com/DennisSSDev/cyberplay

**Comment by DennisSSDev** [comment]
Update: this issue does not persist upon the build of the next js server. Not sure why though

**Comment by DennisSSDev** [comment]
Update to the update: you can integrate with next using the next jss example, just make sure to wait until the theme provider loads, aka the component "mounts". I used this utility to help me out:
```javascript
export const useLoaded = () => {
    const [loaded, setLoaded] = useState(false);
    useEffect(() => setLoaded(true), []);
    return loaded;
};
```

**Comment by romelperez** [comment]
Hey! The current public version uses a version of JSS which throws a warning because of a rule in one of the components. But it is a warning, it should still work in production.
