### ISSUE TITLE
Docs missing for theming

### ISSUE THREAD

**Issue by vjrasane** [arwes/arwes#49]
The link at page

https://arwes.dev/docs/design-system

for docs regarding creating styles is broken. It points to:

https://github.com/arwes/arwes/blob/master/src/tools/createTheme/theme.js

**Comment by romelperez** [comment]
Hi @vjrasane, yes, it has to point to the current public `arwes` package in the branch [`version1-breakpoint1`](https://github.com/arwes/arwes/tree/version1-breakpoint1).

The URL should be: [`https://github.com/arwes/arwes/blob/version1-breakpoint1/src/tools/createTheme/theme.js`](https://github.com/arwes/arwes/blob/version1-breakpoint1/src/tools/createTheme/theme.js).

**Comment by romelperez** [comment]
The website was moved to https://version1-breakpoint1.arwes.dev/docs/design-system and this issue was fixed.
