### ISSUE TITLE
Form Design Proposal [feature]

### ISSUE THREAD

**Issue by njwest** [arwes/arwes#5]
#### 800px by 600px view:

![with-buttons](https://user-images.githubusercontent.com/3742496/40961904-85311bf0-68d6-11e8-830d-38d93d2544de.png)

### JSX Design

```javascript
<Frame>
  <Form>
    <FormTitle>FORM</FormTitle>

    <FormGroup>
        <Label>PLANET</Label>
        <TextInput />
    </FormGroup>

    <FormGroup>
        <Label>SYSTEM</Label>
        <TextInput />
    </FormGroup>

    <FormGroup>
        <Label>GALAXY</Label>
        <TextInput />
    </FormGroup>

    <FormGroup>
        <Label>DIMENSION</Label>
        <TextInput />
    </FormGroup>

    <FormButtons>
      <Button onClick={ [some submit code here] }>
        Submit 
      </Button> 
      <Button onClick={ [some redirect to previous route code here]}>
        Cancel
      </Button>
    </FormButtons>
  </Form>
</Frame>

```

### Component style overview

- `<FormTitle>` is basically a Header but centered
- `<FormGroup>` is parent of Labels + Inputs, so Label + Inputs fall inline-block
- `<Label>` has the styles of the **Intergalactic Link**, highlighted when its sibling `<TextInput/>` is **active**
-  `<Label>` also ends with a `:` by default, and all Labels are justifed to the right, with all `:` (colons) aligned
- When active, `<TextInput/>` has the blinking text entry light from the   `<Words animate show={anim.entered}>` animation
- `<FormButtons>` contains inline-block submit/cancel/etc <Button>s, is a centered div at end of form

### Pixel Grid View

<img width="817" alt="screen shot 2018-06-05 at 3 37 10 pm" src="https://user-images.githubusercontent.com/3742496/40961908-8ad8aeba-68d6-11e8-96a7-3a381e6c70be.png">

**Comment by njwest** [comment]
Forgot a submit button :P But you get the idea :)

**Comment by njwest** [comment]
@romelperez What do you think of this form style? 

Form labels may be too centered, but I'd def give them hefty margin-left or padding-left to prevent left side overflow in this concept

**Comment by njwest** [comment]
Maybe FormGroups a little more to the left, with blinking text input box right under the F in FORM:

![leftward-a-bit](https://user-images.githubusercontent.com/3742496/40961533-6ebc4184-68d5-11e8-8d8d-142fea77af51.png)

**Comment by romelperez** [comment]
It looks pretty good!

Here are some thoughs on the plan to work on them.

**First**, we need to define how the input elements should work. My idea is to start with the most basic form components: `<input type="text|email|url|number|search|...">`, `<input type="checkbox">`, and `<select>`. Here some inspiration:

Inputs and selects: https://robertsspaceindustries.com/enlist
For checkboxes: https://codepen.io/aaronchuo/pen/adErn

These components should work with the `control` color palette, as the `<Button>` works. The idea is mark them as interactive elements in the application. The animation for the input text you suggest can be tricky to make, but we can research about it :) We can play with the animation for the select and the checkboxes to see what is best for them.

It would be awesome to define what kind of sounds to play when the user interacts with the elements. We need to research about this too. The idea is to follow the rhythms or "style" from the current sounds.

**Second**, we would need to define how the form structure components should work: `<FormTitle>`, `<FormGroup>`, `<Label>`, and `<FormButtons>`. Since these are more about layout, I think they should be straightforward.

I feel more inclined to have the labels in a different line than the inputs, but we can make components to define the kind of structure we want.

**Comment by romelperez** [comment]
First I need to migrate the project to lerna and make some structural changes in the components before coding more components. But we can define how the components can look and work.

What do you think?

**Comment by njwest** [comment]
Sounds great! 

I'll check out the examples provided, then I'll take a close look at how the control color palette works with components in Arwes

> Inputs and selects: https://robertsspaceindustries.com/enlist
> For checkboxes: https://codepen.io/aaronchuo/pen/adErn

> These components should work with the control color palette, as the <Button> works. The idea is mark them as interactive elements in the application. The animation for the input text you suggest can be tricky to make, but we can research about it :) We can play with the animation for the select and the checkboxes to see what is best for them.

**Comment by romelperez** [comment]
For the color palette, it's basically to know what colors to use in the components looks. Here you can check the default colors, they can be overwritten: https://github.com/arwesjs/arwes/blob/master/src/tools/createTheme/theme.js#L38

**Comment by njwest** [comment]
Chévere

**Comment by ReactGirl** [comment]
Is there any timeline to add inputs?

**Comment by romelperez** [comment]
Hi @ReactGirl ! Yes, it would be most likely by the third to fourth quarter of the year.

**Comment by crutchcorn** [comment]
I'd love to take this on if PRs are being accepted for this. (I know it was mentioned that migration to lerna was needed first. Would love to help with that as well if that's something that's needed) 

One of my concerns regarding the design would probably be that I as a user don't know when the input starts or stops. I'd add an underline that could be animated in just to showcase that for users. Also, what of hover states or select states/etc for accessability?

**Comment by romelperez** [comment]
Hi @crutchcorn !

Currently, the project is on hold due to research still being in progress.

The roadmap is still to re-start development on before the end of the second quarter.

Thanks for showing interest in the project. Let's keep in touch Discord at https://discord.gg/s5sbTkw

**Comment by njwest** [comment]
## Re: Blinking input caret

Over the past year I've been knee-deep in VueJS projects and away from web React unfortunately, but I did some caret research (caret === the blinking line (|) when an input is in focus).

Focused input caret properties are not accessible via CSS -- they are defined by the browser itself, so the popular solution for custom terminal-esque web carets is to create a text area outside of the viewable page and a pseudo-text area within the viewable page. Upon clicking the pseudo-text area, browser input focuses on the real text area, and text input is rendered in the pseudo-text area.

In a JS framework, a component containing both a pseudo input and a hidden input sharing the same value state should do the trick -- we just need to be smart about how we hide the real input

### Plain HTML/CSS/JS Example 

[On Github Pages](https://njwest.github.io/custom-input-caret/)
[Example index.html](https://github.com/njwest/custom-input-caret/blob/master/index.html)

This example is heavily cribbed from [Shachi's terminal caret example] (http://shachi.prophp.org/demo.html?i=1)

For the hidden text area, `visibility: hidden;` (and `display: none;`, obviously) prevents the browser from focusing on the input.

**Bug in this code:** The pseudo-input does not render more than one blank space character in a row:

<img width="559" alt="Screen Shot 2019-04-25 at 3 08 35 PM" src="https://user-images.githubusercontent.com/3742496/56716157-2e27cd00-676c-11e9-82ca-17d222bae109.png">

**Sidenote:** This code doesn't play well with JSFiddle or CodePen, prob as a result of the window methods in the JS

**Comment by romelperez** [comment]
Hi @njwest ! That proposal looks perfect!
The plan is to start working on Arwes core components by the fourth quarter of 2019.
Soon I'll start planning tasks so we can keep track of these proposals.
Thank you for your contribution!!!

**Comment by romelperez** [comment]
Hello! 👋 

Unfortunately, complete built-in UI components would be out of scope for the release due the effort it has required to built the entire design system. More details in https://github.com/arwes/arwes/issues/46#issuecomment-1639308400.

Thank you all for your interest and patience! 👽
