### ISSUE TITLE
Need input fields for creating some login or feedback forms

### ISSUE THREAD

**Issue by eone666** [arwes/arwes#59]
Need input fields for creating some login or feedback forms in same design

**Comment by romelperez** [comment]
Hello @eone666 !

Check out this ticket https://github.com/arwes/arwes/issues/5 where there are some proposals.

The are plans to add form/control components in the road-map, but currently the development has been paused, soon to be resumed.

Stay tuned!

**Comment by danbopes** [comment]
I love your UI, but without any support for any input controls (Text fields/select dropdowns), it's pretty much useless. No login forms :( No interactivity :( I'm bummed, as I really wanted to use this.

**Comment by romelperez** [comment]
Closed due to https://github.com/arwes/arwes/issues/46#issuecomment-1639308400
