### ISSUE TITLE
Hover animation for Button element not working

### ISSUE THREAD

**Issue by RobertSeidelMuc** [arwes/arwes#60]
## Description

When hovering over button elements, the border color does not change.

## To reproduce

**Live demo**: [Plunkr](https://plnkr.co/edit/exlDweijetJPmHIA?open=Hello.js&deferRun=1&preview)

Code example (placed in index.jsx):
```
import React from "react";
import ReactDOM from "react-dom";
import { ThemeProvider, createTheme, Button, Arwes } from "arwes";

function App() {
  return (
    <ThemeProvider theme={createTheme()}>
      <Arwes>
        <Button>Test</Button>
      </Arwes>
    </ThemeProvider>
  );
}

ReactDOM.render(<App />, document.querySelector("#root"));
```

## Expected behavior

When hovering over a Button element, the border color should brighten, as seen in the Playground

## Development environment

- Packages version: 1.0.0-alpha.5
- OS: Windows 10
- Browser: Chrome 86.0.4240.75; Firefox 82.0b9

## Additional context

I was able to use a workaround by passing the following custom Frame element to Button (note that setting "hover" on true in the Frame element did not work):

```
const ButtonFrame = ({ children }) => {
  const [mouseOver, setMouseOver] = useState(false);
  return (
    <Frame
      corners={1}
      animate={true}
      layer={mouseOver ? "control" : "primary"}
      onMouseEnter={() => setMouseOver(true)}
      onMouseLeave={() => setMouseOver(false)}
    >
      {children}
    </Frame>
  );
};

```

**Comment by romelperez** [comment]
Closed due to https://github.com/arwes/arwes/issues/46#issuecomment-1639308400
