### ISSUE TITLE
Research SEO support for animated components

### ISSUE THREAD

**Issue by romelperez** [arwes/arwes#63]
A public web page using Arwes animation-enabled components should be able to be optimized for web crawling and support SEO recommendations.

Since an animated component by default is mounted with the status "exited" and the HTML elements are usually hidden, there should be research to find out what are the best practices for the website using Arwes to have a good SEO score.

Since a website using Arwes may use SSR (server-side-rendering) when the components are enabled to be animated, an example hypothetical component for a page may look like this:

```html
<main class="main">
    <h1>Bird</h1>
    <p>Birds are a group of warm-blooded vertebrates constituting the class Aves, characterized by feathers, toothless beaked
    jaws, the laying of hard-shelled eggs, a high metabolic rate, a four-chambered heart, and a strong yet lightweight
    skeleton.</p>
</main>
```

The initial styles may be:

```css
.main {
  opacity: 0;
}
```

Using the [anime](https://animejs.com) animation library on page load:

```js
anime({
  targets: document.querySelector('.main'),
  opacity: [0, 1]
});
```

Using the example animated component above:

- [x] Research SEO support and recommendations for animated HTML elements.
- [x] Are there better alternatives to animated components with initial hidden features on page load for SEO purposes?
- [x] Discuss the findings in this ticket.

According to the results of this finding, there may be following tasks.

**Comment by romelperez** [comment]
Google Search Engine supports HTML elements with opacity equals to `0` and still be crawl-able.

**Comment by InsOpDe** [comment]
So does the actual released version support SEO, or do we have to wait for 1.0 to be released?

**Comment by romelperez** [comment]
@InsOpDe, yes! It supports SEO, at least Google Search Engine.

The previous and the new animation API use the same strategy of rendering most animated UI elements with opacity `0`. Only if this is used (or similar CSS properties like `visibility: hidden`), this issue makes sense.
