### ISSUE TITLE
CyberPunk 2022 Social Media in React/Node showcase

### ISSUE THREAD

**Issue by inPhoenix** [arwes/arwes#71]
This is an amazing UI Framework. 

I have developed a futuristic social network using the MERN stack with the arwes framework.

### 
**Live Demo**: https://cybersocial.herokuapp.com/

###
code in: https://github.com/inPhoenix/inCyberPunk2022

Feel free if you think it can be added to the list of the arwes showcases.

**Comment by romelperez** [comment]
Hi @inPhoenix !

Yess! I haven't completed some documentation file structure changes, so when that's done, I'll let you know for you to add it.

Thank you for using Arwes!

**Comment by romelperez** [comment]
Hi @inPhoenix !

I forgot about this long time ago. I can add this project in the projects showcase, would you mind if I do?

**Comment by inPhoenix** [comment]
Yes! Please feel free to add. The project is up and running live always. 24/7.

**Comment by romelperez** [comment]
Awesome! I just added it in the [`dev` branch](https://github.com/arwes/arwes/tree/dev). Thank you for using Arwes!
