### ISSUE TITLE
Add Figure component

### ISSUE THREAD

**Issue by romelperez** [arwes/arwes#87]
Add figure component for image assets. It would be used for medium to big main content images.

- [x] Add `Figure` component.
- [x] Add `src: string | string[]` required prop to define the image URL to load.
  - [x] If array, it represents a list of images by breakpoints as configured by the `ArwesThemeProvider` theme.
  - [x] If array, the image load and render is calculated based on the current screen breakpoints range.
- [x] Add `preload: boolean = false` prop to load the image before rendering it.
  - [x] If enabled, a loader component should be shown while loading.
  - [x] If enabled, an error background should be shown if the load failed.
  - [x] It should support responsive images.
- [x] Add `fluid: boolean = false` prop to control image width.
  - [x] If enabled, should set 100% width.
  - [x] If disabled, should set width to image auto.
- [x] Allow `children` prop as image description.
  - [x] Should work with 1 line short description text content.
  - [x] Should work with long description text content.
- [x] Fix `fluid` enabled container width.

**Comment by ugale-deepak3010** [comment]
Dear friends
I love your work

Till I am facing image relative src problem  previous version

I am installed npm through 1 fab 21 ARWES

and all is working good but Image SRC is not working there show image error and not load image

I am start learning earlier react js inspired from you.
I am also paste your static folder but not work

When I try import wallpaper from '/static....';
It works
But image in same path not work 

Online image path is working but relative not work

Thank you

**Comment by romelperez** [comment]
Hi @ugale-deepak3010 ! This ticket is for the development of a new version for the image component.

If I understand correctly your issue, it is not the component, it is the image URL you are passing to the component which is wrong. Please review in the browser console or network panels to see why it is not working properly.
